---
title: "Mapping"
subtitle: "Homework solution"
author: "DAM"
date: '`r format(Sys.Date(), "%d %B %Y")`'
output: html_document
---

```{r setup, echo=FALSE, warning=FALSE, message = FALSE, results='hide'}
knitr::opts_chunk$set(message = FALSE, warning=FALSE, 
               echo=FALSE, eval=TRUE, fig.path = "./") 
FilePath = "C:/Users/Devan.McGranahan/GoogleDrive/IntroRangeR/12_RasGIS/SpatialData/"
```

```{r packages}
if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, sf, rnaturalearth, rnaturalearthdata)
# 
# if (!require("sp")) install.packages("sp")
  pacman::p_load_current_gh("ropensci/rnaturalearthhires")
# devtools::install_github("ropensci/rnaturalearthhires")
```

```{r national}
# Load Natural Earth data for Canada as sf
  ca_provs <- ne_states(country = "Canada", 
                        returnclass = "sf") %>%
                st_transform(26913)
# Load EPA ecoregions for North America
    epa_fp = paste(FilePath, "EPA_NA/NA_CEC_Eco_Level2.shp", sep="")
    EPA_NA <- read_sf(epa_fp) 
# Crop to Canada, transform projection 
  ca_epa <- 
    EPA_NA %>% 
      st_transform(26913) %>%
        st_intersection(ca_provs) 
# Make Canadian Level 1 map
  ca_epa %>%
    mutate(area = st_area(.) ) %>% 
      group_by(NA_L1NAME) %>% 
    summarise()%>%
    filter(NA_L1NAME != "WATER") %>%
  ggplot() + theme_bw() + 
    geom_sf(data=ca_provs, fill="white", color=NA) + 
      geom_sf(aes(fill=NA_L1NAME)) +
      geom_sf(data=ca_provs, fill=NA, color="grey50") + 
    theme(axis.text = element_blank(), 
          axis.ticks = element_blank()) +
  scale_fill_viridis_d("Level 1 Ecoregion", direction = -1) 
```
```{r provincial}
##
##  Provincial map
##
#
# Canadian geographical data at provincial level
  # Alberta
    ab_fp = paste(FilePath, "Canada/cgn_ab_shp_eng.shp", sep="")
    ab_sf <- read_sf(ab_fp)  %>%
                mutate(Province = "Alberta")
  # Saskatchewan
    sk_fp = paste(FilePath, "Canada/cgn_sk_shp_eng.shp", sep="")
    sk_sf <- read_sf(sk_fp) %>%
                mutate(Province = "Saskatchewan")
# Combine provincial geo datasets
  prov_geo <- rbind(ab_sf, sk_sf)
# Vector of desired populated places
  can_cities = c("Calgary", "Edmonton", "Fort McMurray", "Medicine Hat", 
                 "Saskatoon", "Regina", "Prince Albert", "Uranium City")
# Get geo data for desired cities
  cities_sf <-
    prov_geo %>%
      filter(CATEGORY == "Populated Place", 
             GEONAME %in% can_cities) %>%
        select(GEONAME, Province) %>%
          st_transform(26913) 
# Get boundaries for provinces of desired cities
  provs_sf <- ca_provs %>%
              filter(name %in% cities_sf$Province) %>%
                select(name, postal)
# Crop ecoregion data to provinces, dissolve
  prov_epa <-
    ca_epa%>%
      st_intersection(provs_sf) %>%
      mutate(area = st_area(.) ) %>% 
      group_by(NA_L2NAME) %>% 
      summarise()%>%
      filter(NA_L2NAME != "WATER") 
# Create AK + SK Level 2 map 
  ggplot() + theme_bw() + 
    geom_sf(data=prov_epa, 
            aes(fill=NA_L2NAME), color=NA) + 
    geom_sf(data=provs_sf, 
            fill=NA, color="white") + 
    geom_sf_label(data=cities_sf, 
                  aes(label=GEONAME), 
                  color="black", size=3, 
                  label.padding = unit(0.15, "lines"), 
                  nudge_y = -(10^4.75)) +
    geom_sf(data=cities_sf, 
            color="white", pch=4, stroke=2.5, size=2) +
    geom_sf_text(data=provs_sf, 
                  aes(label=name), 
                 color="white", fontface="bold", size=5) +  
    theme(axis.text = element_blank(), 
          axis.title = element_blank(),
          axis.ticks = element_blank()) +
    scale_fill_viridis_d("Level 2 Ecoregion", direction = 1)  
```

## Script

```{r script, ref.label=knitr::all_labels(!label %in% c('setup') ), echo=TRUE,eval=FALSE}
```
